GET http://localhost:3030/profile

###

POST http://localhost:3030/profile
Content-Type: application/json

{
    "name": "testing again delete",
    "rating": "5/5",
    "genre": "Thriller"
}

###
DELETE http://localhost:3030/post/delete/633053a79b5abe42c7e7fb39